import re
import json

with open('lib/store.ts', 'r', encoding='utf-8') as f:
    content = f.read()

# Define exact correct order for Apple models
apple_models_correct = [
  {"id": "m-apple-apple-iphone-17-pro-max", "brandId": "b-apple", "brandSlug": "apple", "name": "Apple iPhone 17 Pro Max", "slug": "apple-iphone-17-pro-max", "imageUrl": "https://s3ng.cashify.in/cashify/product/img/xhdpi/c90a2a0b-fcc8.jpg?w=800", "releaseYear": 2025, "popular": False, "active": True, "contactForPrice": False, "category": "MOBILE"},
  {"id": "m-apple-apple-iphone-17-pro", "brandId": "b-apple", "brandSlug": "apple", "name": "Apple iPhone 17 Pro", "slug": "apple-iphone-17-pro", "imageUrl": "https://s3ng.cashify.in/cashify/product/img/xhdpi/eeee646c-8046.jpg?w=800", "releaseYear": 2025, "popular": False, "active": True, "contactForPrice": False, "category": "MOBILE"},
  {"id": "m-apple-apple-iphone-17", "brandId": "b-apple", "brandSlug": "apple", "name": "Apple iPhone 17", "slug": "apple-iphone-17", "imageUrl": "https://s3ng.cashify.in/cashify/product/img/xhdpi/ac41123f-6b8f.jpg?w=800", "releaseYear": 2025, "popular": False, "active": True, "contactForPrice": False, "category": "MOBILE"},
  {"id": "m-apple-apple-iphone-17e", "brandId": "b-apple", "brandSlug": "apple", "name": "Apple iPhone 17e", "slug": "apple-iphone-17e", "imageUrl": "https://s3ng.cashify.in/cashify/product/img/xhdpi/27277a1f-37f5.jpg?w=800", "releaseYear": 2025, "popular": False, "active": True, "contactForPrice": False, "category": "MOBILE"},
  {"id": "m-apple-apple-iphone-air", "brandId": "b-apple", "brandSlug": "apple", "name": "Apple iPhone Air", "slug": "apple-iphone-air", "imageUrl": "https://s3ng.cashify.in/cashify/product/img/xhdpi/32e3bec8-29f9.jpg?w=800", "releaseYear": 2025, "popular": False, "active": True, "contactForPrice": False, "category": "MOBILE"},
  {"id": "m-apple-apple-iphone-16", "brandId": "b-apple", "brandSlug": "apple", "name": "Apple iPhone 16", "slug": "apple-iphone-16", "imageUrl": "https://s3ng.cashify.in/cashify/product/img/xhdpi/db36cde6-e6e5.jpg?w=800", "releaseYear": 2024, "popular": False, "active": True, "contactForPrice": False, "category": "MOBILE"},
  {"id": "m-apple-apple-iphone-16e", "brandId": "b-apple", "brandSlug": "apple", "name": "Apple iPhone 16e", "slug": "apple-iphone-16e", "imageUrl": "https://s3ng.cashify.in/cashify/product/img/xhdpi/ed91ebeb-f711.jpg?w=800", "releaseYear": 2024, "popular": False, "active": True, "contactForPrice": False, "category": "MOBILE"},
  {"id": "m-apple-apple-iphone-16-plus", "brandId": "b-apple", "brandSlug": "apple", "name": "Apple iPhone 16 Plus", "slug": "apple-iphone-16-plus", "imageUrl": "https://s3ng.cashify.in/cashify/product/img/xhdpi/5c48706b-b04d.jpg?w=800", "releaseYear": 2024, "popular": False, "active": True, "contactForPrice": False, "category": "MOBILE"},
  {"id": "m-apple-apple-iphone-16-pro", "brandId": "b-apple", "brandSlug": "apple", "name": "Apple iPhone 16 Pro", "slug": "apple-iphone-16-pro", "imageUrl": "https://s3ng.cashify.in/cashify/product/img/xhdpi/c6842e95-7635.jpg?w=800", "releaseYear": 2024, "popular": False, "active": True, "contactForPrice": False, "category": "MOBILE"},
  {"id": "m-apple-apple-iphone-16-pro-max", "brandId": "b-apple", "brandSlug": "apple", "name": "Apple iPhone 16 Pro Max", "slug": "apple-iphone-16-pro-max", "imageUrl": "https://s3ng.cashify.in/cashify/product/img/xhdpi/d197ee88-ccff.jpg?w=800", "releaseYear": 2024, "popular": False, "active": True, "contactForPrice": False, "category": "MOBILE"},
  {"id": "m-apple-apple-iphone-15", "brandId": "b-apple", "brandSlug": "apple", "name": "Apple iPhone 15", "slug": "apple-iphone-15", "imageUrl": "https://s3ng.cashify.in/cashify/product/img/xhdpi/e2c7dff8-23a0.jpg?w=800", "releaseYear": 2023, "popular": True, "active": True, "contactForPrice": False, "category": "MOBILE"},
  {"id": "m-apple-apple-iphone-15-plus", "brandId": "b-apple", "brandSlug": "apple", "name": "Apple iPhone 15 Plus", "slug": "apple-iphone-15-plus", "imageUrl": "https://s3ng.cashify.in/cashify/product/img/xhdpi/a6db4974-1a86.jpg?w=800", "releaseYear": 2023, "popular": True, "active": True, "contactForPrice": False, "category": "MOBILE"},
  {"id": "m-apple-apple-iphone-15-pro", "brandId": "b-apple", "brandSlug": "apple", "name": "Apple iPhone 15 Pro", "slug": "apple-iphone-15-pro", "imageUrl": "https://s3ng.cashify.in/cashify/product/img/xhdpi/f43b6269-c954.jpg?w=800", "releaseYear": 2023, "popular": True, "active": True, "contactForPrice": False, "category": "MOBILE"},
  {"id": "m-apple-apple-iphone-15-pro-max", "brandId": "b-apple", "brandSlug": "apple", "name": "Apple iPhone 15 Pro Max", "slug": "apple-iphone-15-pro-max", "imageUrl": "https://s3ng.cashify.in/cashify/product/img/xhdpi/e14bb4d9-988f.jpg?w=800", "releaseYear": 2023, "popular": True, "active": True, "contactForPrice": False, "category": "MOBILE"},
  {"id": "m-apple-apple-iphone-14", "brandId": "b-apple", "brandSlug": "apple", "name": "Apple iPhone 14", "slug": "apple-iphone-14", "imageUrl": "https://s3ng.cashify.in/cashify/product/img/xhdpi/36ea82c3-6d6a.jpg?w=800", "releaseYear": 2022, "popular": True, "active": True, "contactForPrice": False, "category": "MOBILE"},
  {"id": "m-apple-apple-iphone-14-plus", "brandId": "b-apple", "brandSlug": "apple", "name": "Apple iPhone 14 Plus", "slug": "apple-iphone-14-plus", "imageUrl": "https://s3ng.cashify.in/cashify/product/img/xhdpi/5fc412f4-2fb5.jpg?w=800", "releaseYear": 2022, "popular": True, "active": True, "contactForPrice": False, "category": "MOBILE"},
  {"id": "m-apple-apple-iphone-14-pro", "brandId": "b-apple", "brandSlug": "apple", "name": "Apple iPhone 14 Pro", "slug": "apple-iphone-14-pro", "imageUrl": "https://s3ng.cashify.in/cashify/product/img/xhdpi/726bfa22-cbfb.jpg?w=800", "releaseYear": 2022, "popular": True, "active": True, "contactForPrice": False, "category": "MOBILE"},
  {"id": "m-apple-apple-iphone-14-pro-max", "brandId": "b-apple", "brandSlug": "apple", "name": "Apple iPhone 14 Pro Max", "slug": "apple-iphone-14-pro-max", "imageUrl": "https://s3ng.cashify.in/cashify/product/img/xhdpi/379a739a-b9df.jpg?w=800", "releaseYear": 2022, "popular": True, "active": True, "contactForPrice": False, "category": "MOBILE"},
  {"id": "m-apple-apple-iphone-13", "brandId": "b-apple", "brandSlug": "apple", "name": "Apple iPhone 13", "slug": "apple-iphone-13", "imageUrl": "https://s3ng.cashify.in/cashify/product/img/xhdpi/96a67b00-9389.jpg?w=800", "releaseYear": 2021, "popular": False, "active": True, "contactForPrice": False, "category": "MOBILE"},
  {"id": "m-apple-apple-iphone-13-mini", "brandId": "b-apple", "brandSlug": "apple", "name": "Apple iPhone 13 Mini", "slug": "apple-iphone-13-mini", "imageUrl": "https://s3ng.cashify.in/cashify/product/img/xhdpi/e6d78dcb-e5c9.jpg?w=800", "releaseYear": 2021, "popular": False, "active": True, "contactForPrice": False, "category": "MOBILE"},
  {"id": "m-apple-apple-iphone-13-pro", "brandId": "b-apple", "brandSlug": "apple", "name": "Apple iPhone 13 Pro", "slug": "apple-iphone-13-pro", "imageUrl": "https://s3ng.cashify.in/cashify/product/img/xhdpi/d2daf417-65fa.jpg?w=800", "releaseYear": 2021, "popular": False, "active": True, "contactForPrice": False, "category": "MOBILE"},
  {"id": "m-apple-apple-iphone-13-pro-max", "brandId": "b-apple", "brandSlug": "apple", "name": "Apple iPhone 13 Pro Max", "slug": "apple-iphone-13-pro-max", "imageUrl": "https://s3ng.cashify.in/cashify/product/img/xhdpi/d89cfed9-63d2.jpg?w=800", "releaseYear": 2021, "popular": False, "active": True, "contactForPrice": False, "category": "MOBILE"},
  {"id": "m-apple-apple-iphone-12", "brandId": "b-apple", "brandSlug": "apple", "name": "Apple iPhone 12", "slug": "apple-iphone-12", "imageUrl": "https://s3ng.cashify.in/cashify/product/img/xhdpi/bf8ed21e-96c9.jpg?w=800", "releaseYear": 2020, "popular": False, "active": True, "contactForPrice": False, "category": "MOBILE"},
  {"id": "m-apple-apple-iphone-12-mini", "brandId": "b-apple", "brandSlug": "apple", "name": "Apple iPhone 12 Mini", "slug": "apple-iphone-12-mini", "imageUrl": "https://s3ng.cashify.in/cashify/product/img/xhdpi/1b4543b6-be95.jpg?w=800", "releaseYear": 2020, "popular": False, "active": True, "contactForPrice": False, "category": "MOBILE"},
  {"id": "m-apple-apple-iphone-12-pro", "brandId": "b-apple", "brandSlug": "apple", "name": "Apple iPhone 12 Pro", "slug": "apple-iphone-12-pro", "imageUrl": "https://s3ng.cashify.in/cashify/product/img/xhdpi/584e10e9-d0df.jpg?w=800", "releaseYear": 2020, "popular": False, "active": True, "contactForPrice": False, "category": "MOBILE"},
  {"id": "m-apple-apple-iphone-12-pro-max", "brandId": "b-apple", "brandSlug": "apple", "name": "Apple iPhone 12 Pro Max", "slug": "apple-iphone-12-pro-max", "imageUrl": "https://s3ng.cashify.in/cashify/product/img/xhdpi/5b276976-cfb2.jpg?w=800", "releaseYear": 2020, "popular": False, "active": True, "contactForPrice": False, "category": "MOBILE"},
  {"id": "m-apple-apple-iphone-11", "brandId": "b-apple", "brandSlug": "apple", "name": "Apple iPhone 11", "slug": "apple-iphone-11", "imageUrl": "https://s3ng.cashify.in/cashify/product/img/xhdpi/d8394bf8-e922.jpg?w=800", "releaseYear": 2019, "popular": True, "active": True, "contactForPrice": False, "category": "MOBILE"},
  {"id": "m-apple-apple-iphone-11-pro", "brandId": "b-apple", "brandSlug": "apple", "name": "Apple iPhone 11 Pro", "slug": "apple-iphone-11-pro", "imageUrl": "https://s3ng.cashify.in/cashify/product/img/xhdpi/83ff20f9-b7bc.jpg?w=800", "releaseYear": 2019, "popular": True, "active": True, "contactForPrice": False, "category": "MOBILE"},
  {"id": "m-apple-apple-iphone-11-pro-max", "brandId": "b-apple", "brandSlug": "apple", "name": "Apple iPhone 11 Pro Max", "slug": "apple-iphone-11-pro-max", "imageUrl": "https://s3ng.cashify.in/cashify/product/img/xhdpi/c88dec9d-73d5.jpg?w=800", "releaseYear": 2019, "popular": True, "active": True, "contactForPrice": False, "category": "MOBILE"},
  {"id": "m-apple-apple-iphone-xr", "brandId": "b-apple", "brandSlug": "apple", "name": "Apple iPhone XR", "slug": "apple-iphone-xr", "imageUrl": "https://s3ng.cashify.in/cashify/product/img/xhdpi/55237aff-b449.jpg?w=800", "releaseYear": 2018, "popular": True, "active": True, "contactForPrice": False, "category": "MOBILE"},
  {"id": "m-apple-apple-iphone-xs", "brandId": "b-apple", "brandSlug": "apple", "name": "Apple iPhone XS", "slug": "apple-iphone-xs", "imageUrl": "https://s3ng.cashify.in/cashify/product/img/xhdpi/a65b64fe-1d9c.jpg?w=800", "releaseYear": 2018, "popular": True, "active": True, "contactForPrice": False, "category": "MOBILE"},
  {"id": "m-apple-apple-iphone-xs-max", "brandId": "b-apple", "brandSlug": "apple", "name": "Apple iPhone XS Max", "slug": "apple-iphone-xs-max", "imageUrl": "https://s3ng.cashify.in/cashify/product/img/xhdpi/c617215b-2b94.jpg?w=800", "releaseYear": 2018, "popular": True, "active": True, "contactForPrice": False, "category": "MOBILE"},
  {"id": "m-apple-apple-iphone-x", "brandId": "b-apple", "brandSlug": "apple", "name": "Apple iPhone X", "slug": "apple-iphone-x", "imageUrl": "https://s3ng.cashify.in/cashify/product/img/xhdpi/csh-msmkdhpw-iluq.png?w=800", "releaseYear": 2017, "popular": True, "active": True, "contactForPrice": False, "category": "MOBILE"},
  {"id": "m-apple-apple-iphone-8", "brandId": "b-apple", "brandSlug": "apple", "name": "Apple iPhone 8", "slug": "apple-iphone-8", "imageUrl": "https://s3ng.cashify.in/cashify/product/img/xhdpi/csh-wwiz6qsn-dquh.png?w=800", "releaseYear": 2017, "popular": True, "active": True, "contactForPrice": False, "category": "MOBILE"},
  {"id": "m-apple-apple-iphone-8-plus", "brandId": "b-apple", "brandSlug": "apple", "name": "Apple iPhone 8 Plus", "slug": "apple-iphone-8-plus", "imageUrl": "https://s3ng.cashify.in/cashify/product/img/xhdpi/csh-jcko8mvm-sf7x.png?w=800", "releaseYear": 2017, "popular": True, "active": True, "contactForPrice": False, "category": "MOBILE"},
  {"id": "m-apple-apple-iphone-7", "brandId": "b-apple", "brandSlug": "apple", "name": "Apple iPhone 7", "slug": "apple-iphone-7", "imageUrl": "https://s3ng.cashify.in/cashify/product/img/xhdpi/csh-jwihkccb-gqpj.png?w=800", "releaseYear": 2016, "popular": True, "active": True, "contactForPrice": False, "category": "MOBILE"},
  {"id": "m-apple-apple-iphone-7-plus", "brandId": "b-apple", "brandSlug": "apple", "name": "Apple iPhone 7 Plus", "slug": "apple-iphone-7-plus", "imageUrl": "https://s3ng.cashify.in/cashify/product/img/xhdpi/csh-ujdaoxqa-5pv1.png?w=800", "releaseYear": 2016, "popular": True, "active": True, "contactForPrice": False, "category": "MOBILE"},
  {"id": "m-apple-apple-iphone-se-1st-generation", "brandId": "b-apple", "brandSlug": "apple", "name": "Apple iPhone SE 1st Generation", "slug": "apple-iphone-se-1st-generation", "imageUrl": "https://s3ng.cashify.in/cashify/product/img/xhdpi/csh-b3sceh1m-qzme.png?w=800", "releaseYear": 2016, "popular": True, "active": True, "contactForPrice": False, "category": "MOBILE"},
  {"id": "m-apple-apple-iphone-6s", "brandId": "b-apple", "brandSlug": "apple", "name": "Apple iPhone 6S", "slug": "apple-iphone-6s", "imageUrl": "https://s3ng.cashify.in/cashify/product/img/xhdpi/csh-oh9xlwt8-yunr.png?w=800", "releaseYear": 2015, "popular": True, "active": True, "contactForPrice": False, "category": "MOBILE"},
  {"id": "m-apple-apple-iphone-6s-plus", "brandId": "b-apple", "brandSlug": "apple", "name": "Apple iPhone 6S Plus", "slug": "apple-iphone-6s-plus", "imageUrl": "https://s3ng.cashify.in/cashify/product/img/xhdpi/csh-73kjnouo-hzvn.png?w=800", "releaseYear": 2015, "popular": True, "active": True, "contactForPrice": False, "category": "MOBILE"},
  {"id": "m-apple-apple-iphone-6", "brandId": "b-apple", "brandSlug": "apple", "name": "Apple iPhone 6", "slug": "apple-iphone-6", "imageUrl": "https://s3ng.cashify.in/cashify/product/img/xhdpi/csh-qp4ba4sq-aeny.png?w=800", "releaseYear": 2014, "popular": True, "active": True, "contactForPrice": False, "category": "MOBILE"},
  {"id": "m-apple-apple-iphone-6-plus", "brandId": "b-apple", "brandSlug": "apple", "name": "Apple iPhone 6 Plus", "slug": "apple-iphone-6-plus", "imageUrl": "https://s3ng.cashify.in/cashify/product/img/xhdpi/csh-yicxxl1r-d1ta.png?w=800", "releaseYear": 2014, "popular": True, "active": True, "contactForPrice": False, "category": "MOBILE"}
]

# Find all existing Apple models in content and replace them with apple_models_correct
# Find the start of MOBILE_MODELS_PART_1 or Apple entries
apple_json_str = ",\n  ".join([json.dumps(m) for m in apple_models_correct])

# Replace all Apple entries in store.ts with apple_json_str
# First remove any object with "brandSlug": "apple"
new_content = re.sub(r'\{\s*"id"\s*:\s*"m-apple-[^"]+"[^\}]+\}\s*,?', '', content)

# Remove any orphaned empty lines
new_content = re.sub(r'\n\s*\n\s*\n', '\n\n', new_content)

# Insert clean apple_models_correct right after `const MOBILE_MODELS_PART_1: DeviceModelData[] = [\n`
part1_idx = new_content.find("const MOBILE_MODELS_PART_1: DeviceModelData[] = [")
if part1_idx != -1:
    insert_pos = new_content.find("[", part1_idx) + 1
    new_content = new_content[:insert_pos] + "\n  " + apple_json_str + ",\n" + new_content[insert_pos:]

with open('lib/store.ts', 'w', encoding='utf-8') as f:
    f.write(new_content)

print("Successfully replaced Apple models sequence in store.ts!")
