"use client";

import React, { useState, useEffect } from "react";
import { AdminSidebar } from "@/components/admin/AdminSidebar";
import { Badge } from "@/components/ui/Badge";
import { FileText, Smartphone, Loader2 } from "lucide-react";

interface Quote {
  id: string;
  quoteNumber: string;
  deviceName: string;
  basePrice: number;
  estimatedPrice: number;
  status: string;
  createdAt: string;
}

export default function AdminQuotesPage() {
  const [quotes, setQuotes] = useState<Quote[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    const fetchQuotes = async () => {
      try {
        const session = typeof window !== "undefined"
          ? JSON.parse(localStorage.getItem("cashall_admin_session") || "{}")
          : {};
        const token = session?.token || "";

        const res = await fetch("/api/v1/admin/quotes", {
          headers: token ? { Authorization: `Bearer ${token}` } : {},
        });
        if (res.ok) {
          const data = await res.json();
          setQuotes(data.quotes || []);
        } else {
          setQuotes([]);
        }
      } catch (err: any) {
        setQuotes([]);
      } finally {
        setLoading(false);
      }
    };
    fetchQuotes();
  }, []);

  const formatDate = (iso: string) => {
    try {
      return new Date(iso).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" });
    } catch {
      return iso;
    }
  };

  return (
    <div className="min-h-screen bg-brand-bg flex">
      <AdminSidebar />

      <main className="flex-grow p-8 overflow-y-auto space-y-8">
        <div>
          <h1 className="text-2xl font-black text-brand-black">Quotes Snapshot Repository</h1>
          <p className="text-xs text-brand-muted mt-0.5">
            Audit historical valuation snapshots generated by customers
          </p>
        </div>

        <div className="bg-white rounded-3xl p-6 border border-brand-border shadow-premium overflow-x-auto">
          {loading && (
            <div className="flex items-center justify-center py-16">
              <Loader2 className="w-5 h-5 animate-spin text-brand-yellow" />
              <span className="ml-2 text-xs text-brand-muted font-semibold">Loading quotes...</span>
            </div>
          )}

          {error && (
            <div className="bg-red-50 border border-red-200 text-red-700 text-xs p-4 rounded-2xl font-semibold">
              {error}
            </div>
          )}

          {!loading && !error && quotes.length === 0 && (
            <div className="text-center py-16 text-brand-muted">
              <FileText className="w-10 h-10 mx-auto mb-3 opacity-25" />
              <p className="text-sm font-bold">No quotes yet</p>
              <p className="text-xs mt-1">Customer valuation quotes will appear here once they assess a device.</p>
            </div>
          )}

          {!loading && !error && quotes.length > 0 && (
            <table className="w-full text-left text-xs">
              <thead>
                <tr className="bg-gray-50 text-gray-400 font-bold uppercase tracking-wider border-b border-gray-100">
                  <th className="p-3">Quote ID</th>
                  <th className="p-3">Device / Variant</th>
                  <th className="p-3">Base Price</th>
                  <th className="p-3">Estimated CashALL Value</th>
                  <th className="p-3">Status</th>
                  <th className="p-3">Generated</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-100">
                {quotes.map((q) => (
                  <tr key={q.id} className="hover:bg-gray-50/80 transition-colors">
                    <td className="p-3 font-extrabold text-brand-black">{q.quoteNumber}</td>
                    <td className="p-3 font-bold text-brand-black flex items-center gap-2">
                      <Smartphone className="w-4 h-4 text-brand-yellow shrink-0" />
                      <span>{q.deviceName}</span>
                    </td>
                    <td className="p-3 font-price font-semibold text-gray-500">₹{q.basePrice.toLocaleString("en-IN")}</td>
                    <td className="p-3 font-price font-extrabold text-brand-black">₹{q.estimatedPrice.toLocaleString("en-IN")}</td>
                    <td className="p-3">
                      <Badge variant={q.status === "ORDERED" ? "success" : "yellow"}>{q.status}</Badge>
                    </td>
                    <td className="p-3 text-gray-400 font-medium">{formatDate(q.createdAt)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>
      </main>
    </div>
  );
}
