"use client";

import React from "react";
import { AdminSidebar } from "@/components/admin/AdminSidebar";
import { Badge } from "@/components/ui/Badge";
import { FileText, Smartphone } from "lucide-react";

export default function AdminQuotesPage() {
  const quotes = [
    { id: "q-1", quoteNumber: "CAQ-984210", device: "iPhone 15 (128GB)", base: 32000, estimated: 31400, status: "ACTIVE", created: "Today" },
    { id: "q-2", quoteNumber: "CAQ-771402", device: "Galaxy S24 Ultra (256GB)", base: 58000, estimated: 54200, status: "ORDERED", created: "Yesterday" },
    { id: "q-3", quoteNumber: "CAQ-661093", device: "OnePlus 12 (256GB)", base: 28000, estimated: 26500, status: "ACTIVE", created: "2 days ago" },
  ];

  return (
    <div className="min-h-screen bg-brand-bg flex">
      <AdminSidebar />

      <main className="flex-grow p-8 overflow-y-auto space-y-8">
        <div>
          <h1 className="text-2xl font-black text-brand-black">
            Quotes Snapshot Repository
          </h1>
          <p className="text-xs text-brand-muted mt-0.5">
            Audit historical valuation snapshots generated by customers
          </p>
        </div>

        <div className="bg-white rounded-3xl p-6 border border-brand-border shadow-premium overflow-x-auto">
          <table className="w-full text-left text-xs">
            <thead>
              <tr className="bg-gray-50 text-gray-400 font-bold uppercase tracking-wider border-b border-gray-100">
                <th className="p-3">Quote ID</th>
                <th className="p-3">Device / Variant</th>
                <th className="p-3">Base Price</th>
                <th className="p-3">Estimated CashALL Value</th>
                <th className="p-3">Status</th>
                <th className="p-3">Generated</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {quotes.map((q) => (
                <tr key={q.id} className="hover:bg-gray-50/80 transition-colors">
                  <td className="p-3 font-extrabold text-brand-black">{q.quoteNumber}</td>
                  <td className="p-3 font-bold text-brand-black flex items-center gap-2">
                    <Smartphone className="w-4 h-4 text-brand-yellow" />
                    <span>{q.device}</span>
                  </td>
                  <td className="p-3 font-price font-semibold text-gray-500">₹{q.base.toLocaleString("en-IN")}</td>
                  <td className="p-3 font-price font-extrabold text-brand-black">₹{q.estimated.toLocaleString("en-IN")}</td>
                  <td className="p-3">
                    <Badge variant={q.status === "ORDERED" ? "success" : "yellow"}>{q.status}</Badge>
                  </td>
                  <td className="p-3 text-gray-400 font-medium">{q.created}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </main>
    </div>
  );
}
